/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Conexion;
import Clases.LgnAutores;
import java.sql.Connection;
import java.util.Stack;

/**
 *
 * @author anuar
 */
public class Autores extends javax.swing.JInternalFrame {
    Connection con;

    /**
     * Creates new form Autores
     */
    public Autores() {
        initComponents();
                con=new Conexion().Conectar();
        LgnAutores lgn= new LgnAutores(con, JtxApellidoMater, JtxApellidoPater, JtxNombre,jComboBox1);
        Stack pila= lgn.Nacionalidades();
        while(!pila.empty()){
            jComboBox1.addItem(pila.pop().toString());
        }
        jButton1.addActionListener(lgn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JtxNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JtxApellidoPater = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JtxApellidoMater = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 2, 18)); // NOI18N
        jLabel2.setText("AUTORES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 110, -1));

        jLabel3.setText("Nombre Autor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        JtxNombre.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(JtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 170, -1));

        jLabel4.setText("Apellido Paterno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        JtxApellidoPater.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(JtxApellidoPater, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 170, -1));

        jLabel5.setText("Apellido Materno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        JtxApellidoMater.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.add(JtxApellidoMater, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 170, -1));

        jLabel6.setText("Nacionalidad");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 130, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("GUARDAR");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima/libros.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxApellidoMater;
    private javax.swing.JTextField JtxApellidoPater;
    private javax.swing.JTextField JtxNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
